include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false

analyzer:
  errors:
    prefer_const_constructors: ignore
  exclude:
    - "lib/**.g.dart"
    - "lib/**.config.dart"
