include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    sort_constructors_first: false
    one_member_abstracts: false
    unnecessary_lambdas: false
    lines_longer_than_80_chars: false
    prefer_const_constructors: true

analyzer:
  exclude:
    - "lib/**.g.dart"
    - "lib/**.config.dart"
